name: build-and-test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore Azzu.WebBff.sln -p:NuGetAudit=true -p:NuGetAuditMode=all -warnaserror:NU1901,NU1902,NU1903,NU1904
      - name: Build
        run: dotnet build Azzu.WebBff.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test Azzu.WebBff.sln --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"
          if-no-files-found: warn

